version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    # ports:
    #   - '3000:3000'
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo: # set up mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=poomipat
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes: # create volume to store data 
      - mongo-db:/data/db

  redis:
    image: redis


volumes: # create volume name to prevent to be anonymous volume
  mongo-db: